# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'iryna-slynko'
    scannerMode: 'MSBuild'
    projectKey: 'Iryna-Slynko_CovidVaccineEligibility'
- task: VSBuild@1
  inputs:
    vsVersion: latest
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: BuildQualityChecks@8
  inputs:
    checkWarnings: true
    warningThreshold: '5'
    warningFailOption: 'fixed'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--collect "Code coverage"'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'covid-vaccine'
    scanPath: '**/*.csproj'
    format: 'HTML'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
