trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
jobs:
  - job: RunTests
    steps:
    - task: DotNetCoreCLI@2
      displayName: PublishSeleniumTests
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'SeleniumTests/SeleniumTests.csproj'
        arguments: '--configuration $(BuildConfiguration) --output "$(Build.ArtifactStagingDirectory)\SeleniumTests"'
        zipAfterPublish: false
        
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'iryna-slynko'
        scannerMode: 'MSBuild'
        projectKey: 'Iryna-Slynko_CovidVaccineEligibility'
    - task: DotNetCoreCLI@2
      displayName: PublishWebApp
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output "$(Build.ArtifactStagingDirectory)"'
  
    - task: BuildQualityChecks@8
      inputs:
        checkWarnings: true
        warningThreshold: '5'
        warningFailOption: 'fixed'
      
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        arguments: --collect "Code coverage" --filter 'FullyQualifiedName!~SeleniumTests'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: Copyfiles@2
      inputs:
        Contents: '**/*.runsettings'
        TargetFolder: '$(build.artifactstagingdirectory)/SeleniumTests'
        flattenFolders: true
    - task: Copyfiles@2
      inputs:
        Contents: '**/PerfTest/*.js'
        TargetFolder: '$(build.artifactstagingdirectory)/PerfTest'
        flattenFolders: true
    - task: Copyfiles@2
      inputs:
        Contents: 'zap-config'
        TargetFolder: '$(build.artifactstagingdirectory)/'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
