# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
jobs:
  - job: RunTests
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'iryna-slynko'
        scannerMode: 'MSBuild'
        projectKey: 'Iryna-Slynko_CovidVaccineEligibility'
    - task: VSBuild@1
      inputs:
        vsVersion: latest
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: BuildQualityChecks@8
      inputs:
        checkWarnings: true
        warningThreshold: '5'
        warningFailOption: 'fixed'
      
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        arguments: --collect "Code coverage" --filter 'FullyQualifiedName!~SeleniumTests'
    - task: DotNetCoreCLI@2
      displayName: PublishSeleniumTest
      inputs:
        command: 'publish'
        arguments: --configuration $(BuildConfiguration) --output "$(Build.ArtifactStagingDirectory)\Selenium"'
        publishWebProjects: false
        projects: '**/*SeleniumTests.csproj'
        zipAfterPublish: false
        modifyOutputPath: false
    - task: Copyfiles@2
      inputs:
        Contents: '**/PerfTest/*.js'
        TargetFolder: '$(build.artifactstagingdirectory)/PerfTest'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
