//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Staging : global::System.Configuration.ApplicationSettingsBase {
        
        private static Staging defaultInstance = ((Staging)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Staging())));
        
        public static Staging Default {
            get {
                return defaultInstance;
            }
        }
    }
}
